  stages:
    - build

  maven_build:
    image: maven:3.9.9-eclipse-temurin-21-jammy
    stage: build
    script: "mvn package"
    tags:
      - shared
    artifacts:
      paths:
        - "target/*.jar"

