name: Test and Build

jobs:
  test:
    runs-on: ubuntu-latest
    
    on:
      push:
        branches: [ "main" ]
      pull_request:
        branches: [ "main" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Test
        run: mvn test

  build:
    runs-on: ubuntu-latest
    
    on:
      push:
        branches: [ "main" ]
    
    needs: [test]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build
        run: mvn -B package
